### ISSUE TITLE
Be able to send a string within a message

### ISSUE THREAD

**Issue by mrbonezy** [ton-community/tact#12]
Currently, adding a field of type String will generate an error: 
`String is not allowed to be used as field`

Assuming this is because of variable-length, can we instruct the compiler instead to what length is the string?
Otherwise passing in strings requires a slice which is stored on a separate ref. 

For example, if we want to pass in a 512bit signature, we could send:

```
message MyMsg {
    someData: Int as uint32
    sig: String as bits512;
}
```

**Comment by ex3ndr** [comment]
I think it is already working, and "as bits512" doesn't make sense since it is aboyt bits and not strings. If you want to store binary data, you can store a Slice. Storing fixed-length text strings doesn't make sense as a separate type.

**Comment by mrbonezy** [comment]
Slice is ok, but how do you save it within the same cell? Current implementation seems to put it in a separate ref.

**Comment by ex3ndr** [comment]
Impossible, you can't predict layout with types without defined sizes.

**Comment by mrbonezy** [comment]
What I suggest is to allow to define the size of the slice, which will allow using the cells more efficiently.

**Comment by ex3ndr** [comment]
> What I suggest is to allow to define the size of the slice, which will allow using the cells more efficiently. 

There are some cases for byte aligned byte strings and they are supported, not sure if we need something weird like "272 bytes".

**Comment by mrbonezy** [comment]
> There are some cases for byte aligned byte strings and they are supported

How do I specify a 512bit string?

**Comment by ex3ndr** [comment]
https://github.com/ton-community/tact/blob/0e0d8088809d82e2bffce553cb6b2c92887ad5bc/examples/wallet-opt.tact#L2
https://github.com/ton-community/tact/blob/0e0d8088809d82e2bffce553cb6b2c92887ad5bc/src/storage/resolveAllocation.ts#L98

There are three modifications: bytes32, bytes64 and remaining. Last one reads everything that left and put it into a slice.
