### ISSUE TITLE
Got error when compile this code. Seems ^0.5.0 still can't run with `toString()`

### ISSUE THREAD

**Issue by howardpen9** [ton-community/tact#16]
``````````````

contract Sample {
    balance: Int;
    fwdFee: Int = 0;

   //  receive() {}

    receive("Y") {
    let ctx: Context = context();
    let fwdFee: Int = ctx.readForwardFee();
    self.fwdFee = fwdFee;

    send(SendParameters{
        to: ctx.sender, 
        value: 0, 
        mode: SendIgnoreErrors, 
        bounce: false
        // body: "Already paid".asComment()
    });
}

    receive("1"){
        let ctx: Context = context();
        
        send(SendParameters{
            value: 0, 
            to: ctx.sender, 
            mode: SendRemainingBalance + SendIgnoreErrors, 
            bounce: false 
            // body:  "TTT".asComment()
        });
    }
    
    // get fun ddd(): String{
    //     let b: StringBuilder = beginString();
    //     b.append(self.fwdFee.toString());
    //     return b.toString();
    // }
}

```````````````````

![image](https://user-images.githubusercontent.com/36764495/209602347-4ec517ee-8f43-43f6-b9e8-96f8f7127198.png)

![image](https://user-images.githubusercontent.com/36764495/209602375-545e15c4-d155-43bd-afe4-b33b83d8c7f4.png)

**Comment by howardpen9** [comment]
Got same issued when I compile the code[ rugpull.tact](https://github.com/ton-community/tact/blob/main/examples/rugpull.tact) example


![image](https://user-images.githubusercontent.com/36764495/209603464-6efe5b04-cf83-47e5-9f45-121df0f0496b.png)

**Comment by ex3ndr** [comment]
this is a mixup of ton libraries, should be much better using a new compiler.

Very first screenshot is unfortunately a `func` crash. We are looking for a next release that aimed to solve a lot of crashes.

**Comment by ex3ndr** [comment]
Check the new version (0.7.1) if it would work, but you have to be careful with dependencies, it is better to checkout template first.
