### ISSUE TITLE
Detail explain in `Send.tact`

### ISSUE THREAD

**Issue by tactfunc** [ton-community/tact#17]
# Issued
The words used in this file are not clear enough, especially the difference between SendRemainingBalance and SendRemainingValue.

1. Is the term "RemainingValue" in the function SendRemainingValue referring to the remaining value of the TON (gasToken) at the time the function is called? (Is "Value" referring to the remaining TON value in the transaction?)

2. Does the term "RemainingBalance" in the function SendRemainingBalance refer to the TON balance for the address specified as the to parameter in the function?"

3. What is the Integer value for each modes? 

![image](https://user-images.githubusercontent.com/120684060/209610201-be5fdb81-c53f-43ba-b649-d9f3167a9d3b.png)

**Comment by ex3ndr** [comment]
1) Yes, sending all remaining value of incoming message, yes it is about TON
2) Yes, balance of a contract
3) This values are defined as part of a blockchain
