### ISSUE TITLE
Compile Error on example code

### ISSUE THREAD

**Issue by howardpen9** [ton-community/tact#2]
![image](https://user-images.githubusercontent.com/36764495/209042207-92feb2e5-e1c0-43c8-97bc-0cde5edc0dca.png)

Got error when I tried to compile this code.

**Comment by howardpen9** [comment]
![image](https://user-images.githubusercontent.com/36764495/209042352-e9a4fd01-bc26-4e03-a1e0-abc2464da064.png)

**Comment by ex3ndr** [comment]
Fixed, thanks!
