### ISSUE TITLE
can't get the new error message in @0.8.1

### ISSUE THREAD

**Issue by howardpen9** [ton-community/tact#21]
![image](https://user-images.githubusercontent.com/36764495/211147187-fca123e6-3a20-4517-b839-c12115829f6b.png)

The error since compile

**Comment by howardpen9** [comment]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/36764495/211176077-59cc4daf-fbfb-4b8f-933f-8fd9fb5bf6ae.png">

**Comment by ex3ndr** [comment]
This is exactly what it say
